image: node:18-alpine

# Mise en cache des dépendances pour accélérer les builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

# Fichiers à compresser, et nom de l'application à utiliser
variables:
  FILES_TO_COMPRESS: "htm html txt text js css md ico svg"
  APP_FOLDER: "web"

pages:
  script:
    # Installation des outils de compression
    - apk add --no-cache gzip brotli

    # Création du dossier public qui va contenir tout ce qui est nécessaire pour l'application
    - mkdir .public
    - cp -r * .public
    - mv .public public


    # Construction de l'application
    - cd public
    - npm ci --cache ../.npm --prefer-offline --no-audit
    - npm run build

    # Suppression des éléments inutiles dans public
    - rm -r node_modules

    # L'application est construite dans le répertoire app : on déplace tous les fichiers nécessaires à la racine
    - cd ..
    - cp -r $APP_FOLDER/* public

    # Compression des fichiers spécifiés
    - |
      echo "Compressing files with extensions: $FILES_TO_COMPRESS"
      for ext in $FILES_TO_COMPRESS; do
        find . -type f -name "*.$ext" -exec gzip -k {} \;
        find . -type f -name "*.$ext" -exec brotli {} \;
      done

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
